### ISSUE TITLE
View dataset feature in data processing

### ISSUE THREAD

**Issue by anudeeps0306** [c2siorg/tensormap#13]
**Is your feature request related to a problem? Please describe.**
The "View dataset" feature is currently not implemented. When accessing this component, it appears to load indefinitely without displaying any data.

**Describe the solution you'd like**
I would like to see the "View dataset" feature fully implemented and functional. Upon accessing the component, it should display the dataset promptly and allow users to interact with it as intended.

**Describe alternatives you've considered**

**Additional context**
The successful implementation of the "View dataset" feature is crucial for users to analyze and make use of the available data effectively.

![Screenshot from 2024-02-24 12-56-12](https://github.com/c2siorg/tensormap/assets/71971574/faae65d6-a111-4d0a-be4f-40c803d0888e)

**Comment by Teak-Rosewood** [comment]
#29 adds this feature

**Comment by ivantha** [comment]
Closing as this is fixed.
