### ISSUE TITLE
Fixing Data Processing on Server & Client

### ISSUE THREAD

**Issue by Teak-Rosewood** [c2siorg/tensormap#15]
**Describe the bug**
The Data Processing endpoint in the front end has issue with viewing dataset aswell as seeing the metrics pane.

**To Reproduce**

1. go the the data_process endpoint
2. See error

**Expected behavior**
All Buttons should be working, with the same and dataset should be displayed along with the metrics pane working.

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: Chrome

**Comment by anudeeps0306** [comment]
@Teak-Rosewood, I already implemented this feature #14

**Comment by Teak-Rosewood** [comment]
Hey, didn't notice, since none of the changes have been merged yet, i am guessing a few structures are different from your pull and mine, so I have just added upon master from my previous pull request!

**Comment by Teak-Rosewood** [comment]
#29 implements new features and fixes these issues
