### ISSUE TITLE
Dockerizing Serverside

### ISSUE THREAD

**Issue by Teak-Rosewood** [c2siorg/tensormap#17]
The function involves dockerizing the server side code to run with a single command

**Comment by Teak-Rosewood** [comment]
I am working on this currently

**Comment by anudeeps0306** [comment]
Shouldn't it be part of GSoC?

**Comment by Teak-Rosewood** [comment]
Yup, but seems like a doable task

**Comment by anudeeps0306** [comment]
Since this task is part of GSoC, it's essential to seek approval from the mentor, or matinee, to ensure that the approach taken is correct. I've already dockerized the entire project, but I'm waiting for further suggestions and guidance from the mentor before proceeding.

**Comment by Teak-Rosewood** [comment]
Since its just a PR, I don't see an issue in raising the same
