### ISSUE TITLE
Refactoring Multi-Classification Backend in tensormap Server

### ISSUE THREAD

**Issue by anudeeps0306** [c2siorg/tensormap#28]
We are currently facing issues with the existing backend for multi-classification tasks in tensormap server.

**Comment by anudeeps0306** [comment]
I am currently working on this issue

**Comment by Teak-Rosewood** [comment]
Hey, I was able to compile the backend of the server without any errors, what are the issues you were facing

**Comment by anudeeps0306** [comment]
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by Teak-Rosewood** [comment]
yup i have tested it with a dataset, would be helpful if you could put up a screen shot of the error, i did end up changing a bunch of components from class based to functional, but if an issue existed it seems to have fixed itself

**Comment by anudeeps0306** [comment]
![Screenshot from 2024-03-14 10-56-59](https://github.com/c2siorg/tensormap/assets/71971574/2ab66c93-e505-4527-a697-5d3904eb143e)

**Comment by Teak-Rosewood** [comment]
try changing yaml.load to yaml.safe_load() that function doesnt take in a loader in ModelRun.py, although it seems to working fine on my end

**Comment by anudeeps0306** [comment]
That's not end to issues . I am trying to figure out all issues .

**Comment by Teak-Rosewood** [comment]
My PR seems to fix all the related issues, if there are any other issues do let me know!

**Comment by anudeeps0306** [comment]
Ok
