### ISSUE TITLE
Feature: Row Manipulation Functionality

### ISSUE THREAD

**Issue by anudeeps0306** [c2siorg/tensormap#31]
**Is your feature request related to a problem? Please describe.**
Users currently lack the ability to add, modify, or delete rows within the system/application.

**Additional context**
This feature enhancement would greatly improve the usability and functionality of the system/application, providing users with greater control over their data management tasks.

**Comment by Teak-Rosewood** [comment]
#29 implements this feature

**Comment by ivantha** [comment]
Closing as this is fixed.
