### ISSUE TITLE
 Unable to Validate Model Due to Missing model_func.json File

### ISSUE THREAD

**Issue by anudeeps0306** [c2siorg/tensormap#4]
**Describe the bug**

During the model validation process, the system fails to locate the model_func.json file, which is essential for validation. This file serves as the starting template for the validation process.

**To Reproduce**

1. Go to the Deep Learning model Section and fill in the information
2. Click on Validate Button
3. See error

**Screenshots**
![Screenshot from 2024-02-11 14-47-09](https://github.com/c2siorg/tensormap/assets/71971574/5248bf90-06a7-4ab7-acea-57815d1aa16f)
![Screenshot from 2024-02-11 14-47-26](https://github.com/c2siorg/tensormap/assets/71971574/c236e066-1c51-4690-931a-3af57151d54e)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 22.04

**Additional context**

**Comment by Teak-Rosewood** [comment]
#27 fixes this issue

**Comment by ivantha** [comment]
Closing as this is fixed.
